USE [master]
GO

/****** Object:  Database [Assignment4]    Script Date: 11/22/2016 3:03:17 PM ******/
CREATE DATABASE [Assignment4]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Assignment4', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.SQLEXPRESS\MSSQL\DATA\Assignment4.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Assignment4_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.SQLEXPRESS\MSSQL\DATA\Assignment4_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [Assignment4] SET COMPATIBILITY_LEVEL = 130
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Assignment4].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Assignment4] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Assignment4] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Assignment4] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Assignment4] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Assignment4] SET ARITHABORT OFF 
GO

ALTER DATABASE [Assignment4] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Assignment4] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Assignment4] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Assignment4] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Assignment4] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Assignment4] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Assignment4] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Assignment4] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Assignment4] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Assignment4] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Assignment4] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Assignment4] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Assignment4] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Assignment4] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Assignment4] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Assignment4] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Assignment4] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Assignment4] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Assignment4] SET  MULTI_USER 
GO

ALTER DATABASE [Assignment4] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Assignment4] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Assignment4] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Assignment4] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Assignment4] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Assignment4] SET QUERY_STORE = OFF
GO

USE [Assignment4]
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [Assignment4] SET  READ_WRITE 
GO

